GET http://localhost:3000/api/members

###
GET http://localhost:3000/api/members?team=Asenal

###
GET http://localhost:3000/api/members?team=Reverpool

###
GET http://localhost:3000/api/members?team=Manchester Red


###
GET http://localhost:3000/api/members/1

###
POST http://localhost:3000/api/members
Content-Type: application/json

{
    "name": "Kross",
    "team": "Real Mardird",
    "position": "Center Midfilder",
    "email": "Kross@gmail.com",
    "phoneNumber": "010-kkkk-kkkk",
    "DebutDate": "2008/10/15",
    "birthday": "1990/06/29",
    "profileImage": "Kross.png"
}

###
PUT  http://localhost:3000/api/members/1
Content-Type: application/json

{
    "position": "RW"
}

###
PUT  http://localhost:3000/api/members/2
Content-Type: application/json

{
    "name": "Willom Saliba"
}

###
DELETE  http://localhost:3000/api/members/12