module.exports = [
  {
    id: 1,
    name: "Saka",
    team: "Asenal",
    position: "Right Wing",
    email: "saka@gmail.com",
    phoneNumber: "010-1234-1234",
    DebutDate: "2018/11/30",
    birthday: "2001/09/05",
    profileImage: "saka.png",
  },
  {
    id: 2,
    name: "Saliba",
    team: "Asenal",
    position: "Center Back",
    email: "saliba@gmail.com",
    phoneNumber: "010-1111-2222",
    DebutDate: "2022/08/01",
    birthday: "2001/03/24",
    profileImage: "saliba.png",
  },
  {
    id: 3,
    name: "Rice",
    team: "Asenal",
    position: "Midfilder",
    email: "rice@gmail.com",
    phoneNumber: "010-1245-1987",
    DebutDate: "2018/11/30",
    birthday: "1999/01/14",
    profileImage: "rice.png",
  },
  {
    id: 4,
    name: "Arnold",
    team: "Reverpool",
    position: "Right Back",
    email: "arnold@gmail.com",
    phoneNumber: "010-12xs-aszz",
    DebutDate: "2016/08/01",
    birthday: "1998/10/07",
    profileImage: "Arnold.png",
  },
  {
    id: 5,
    name: "White",
    team: "Asenal",
    position: "Right Back",
    email: "white@gmail.com",
    phoneNumber: "010-wwww-hhhh",
    DebutDate: "2017/09/10",
    birthday: "1997/10/08",
    profileImage: "white.png",
  },
  {
    id: 6,
    name: "Rowe",
    team: "Asenal",
    position: "Left Wing",
    email: "rowe@gmail.com",
    phoneNumber: "010-rrrr-dddd",
    DebutDate: "2018/08/31",
    birthday: "2000/07/28",
    profileImage: "rowe.png",
  },
  {
    id: 7,
    name: "Ødegaard",
    team: "Asenal",
    position: "Attack Midfilder",
    email: "Ødegaard@gmail.com",
    phoneNumber: "010-oooo-qqqq",
    DebutDate: "2017/10/15",
    birthday: "1998/12/17",
    profileImage: "Ødegaard.png",
  },
  {
    id: 8,
    name: "Kimmich",
    team: "Bayern Munich",
    position: "Defend Midfilder",
    email: "Kimmich@gmail.com",
    phoneNumber: "010-qwxxa-xxsa",
    DebutDate: "2013/09/10",
    birthday: "1995/02/08",
    profileImage: "Kimmich.png",
  },
  {
    id: 9,
    name: "Haaland",
    team: "Manchester City",
    position: "Center Foward",
    email: "haaland@gmail.com",
    phoneNumber: "010-hhhh-hhhh",
    DebutDate: "2019/01/18",
    birthday: "2000/07/21",
    profileImage: "Haaland.png",
  },
  {
    id: 10,
    name: "Son Heung-Min",
    team: "Totnam",
    position: "Left Wing",
    email: "Son@gmail.com",
    phoneNumber: "010-ssss-nnnn",
    DebutDate: "2010/07/25",
    birthday: "1992/07/08",
    profileImage: "Son.png",
  },
];
