GET http://localhost:3000/api/members

###
GET http://localhost:3000/api/members?team=Asenal

###
GET http://localhost:3000/api/members?team=Reverpool

###
GET http://localhost:3000/api/members?team=Manchester City


###
POST http://localhost:3000/api/members
Content-Type: application/json

{
    "id": 11,
    "name": "Bellingham",
    "team": "Real Mardird",
    "position": "Center Midfilder",
    "email": "Bellingham@gmail.com",
    "phoneNumber": "010-bbbb-bbbb",
    "DebutDate": "2019/11/15",
    "birthday": "2003/06/29",
    "profileImage": "Bellingham.png"
}